services:
  pyspark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8889:8888"
    volumes:  
      - .:/home/jovyan/work
    networks:
      - library

  mongo-data:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "8082:27017"
    networks:
      - library

networks:
  library:

volumes:
  mongo-db:
    driver: local